name: Twitter Bot

on:
  schedule:
    - cron: "0 15 * * *"   # 9 AM MX
    - cron: "0 0 * * *"    # 6 PM MX
  workflow_dispatch:

permissions:
  contents: write  # 👈 necesario para hacer commit

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar dependencias
        run: pip install tweepy

      - name: Ejecutar bot
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python bot.py
