name: Twitter Bot

on:
  schedule:
    - cron: "0 */12 * * *"   # cada 12 horas (UTC)
  workflow_dispatch:         # permite ejecutarlo manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install tweepy

      - name: Ejecutar bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python bot.py

